#include "acl/math/quat_64.h"
#include "acl/math/vector4_64.h"

namespace clip_01_01
{
	// THIS IS A PLACE HOLDER! USE fbx2cpp TO GENERATE THIS FILE
	// IT IS TOO LARGE TO PUT ON GITHUB AND THE SITUATION IS TEMPORARY
	// UNTIL WE HAVE THE SJSON PARSER WORKING
}

